server:
  port: ${USER_SERVICE_PORT}

spring:
  application:
    name: user-service
  datasource:
    url: ${USER_DB_URL}
    username: ${USER_DB_USERNAME}
    password: ${USER_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        format_sql: true
  profiles:
    active: dev
  config:
    import: optional:file:.env
  flyway:
      enabled: true
      locations: classpath:db/migration
      baseline-on-migrate: true
      clean-disabled: false

logging:
  level:
    com.fooddelivery: DEBUG
    org.springframework.security: DEBUG
    org.flywaydb: DEBUG

app:
  security:
    jwt:
      secret-key: ${USER_JWT_SECRET}
      access-token-expiration: ${USER_ACCESS_TOKEN_EXPIRATION}
      refresh-token-expiration: ${USER_REFRESH_TOKEN_EXPIRATION}

springdoc:
  api-docs:
    path: ${API_DOCS_PATH}
  swagger-ui:
    path: ${SWAGGER_UI_PATH}