version: '3.8'

services:
  # Database for User Service
  postgres-user:
    image: postgres:15
    container_name: postgres-user
    environment:
      POSTGRES_DB: ${POSTGRES_USER_DB}
      POSTGRES_USER: ${POSTGRES_USER_USER}
      POSTGRES_PASSWORD: ${POSTGRES_USER_PASSWORD}
    ports:
      - "${POSTGRES_USER_PORT}:5432"
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
    networks:
      - food-delivery-network


  # Database for Restaurant Service
  postgres-restaurant:
    image: postgres:15
    container_name: postgres-restaurant
    environment:
      POSTGRES_DB: ${POSTGRES_RESTAURANT_DB}
      POSTGRES_USER: ${POSTGRES_RESTAURANT_USER}
      POSTGRES_PASSWORD: ${POSTGRES_RESTAURANT_PASSWORD}
    ports:
      - "${POSTGRES_RESTAURANT_PORT}:5432"
    volumes:
      - postgres_restaurant_data:/var/lib/postgresql/data
    networks:
      - food-delivery-network

  # Database for Order Service
  postgres-order:
    image: postgres:15
    container_name: postgres-order
    environment:
      POSTGRES_DB: ${POSTGRES_ORDER_DB}
      POSTGRES_USER: ${POSTGRES_ORDER_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ORDER_PASSWORD}
    ports:
      - "${POSTGRES_ORDER_PORT}:5432"
    volumes:
      - postgres_order_data:/var/lib/postgresql/data
    networks:
      - food-delivery-network

volumes:
  postgres_user_data:
  postgres_restaurant_data:
  postgres_order_data:

networks:
  food-delivery-network:
    driver: bridge