server:
  port: ${ORDER_SERVICE_PORT}

spring:
  application:
    name: order-service
  datasource:
    url: ${ORDER_DB_URL}
    username: ${ORDER_DB_USERNAME}
    password: ${ORDER_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        format_sql: true
  profiles:
    active: dev
  config:
    import: optional:file:.env
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: false
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

logging:
  level:
    com.fooddelivery: DEBUG
    org.flywaydb: DEBUG
app:
  security:
    jwt:
      secret-key: ${ORDER_JWT_SECRET}

springdoc:
  api-docs:
    path: ${API_DOCS_PATH}
  swagger-ui:
    path: ${SWAGGER_UI_PATH}