server:
  port: ${RESTAURANT_SERVICE_PORT}

spring:
  application:
    name: restaurant-service
  datasource:
    url: ${RESTAURANT_DB_URL}
    username: ${RESTAURANT_DB_USERNAME}
    password: ${RESTAURANT_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        format_sql: true
  profiles:
    active: dev
  config:
    import: optional:file:.env
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: false

logging:
  level:
    com.fooddelivery: DEBUG
    org.flywaydb: DEBUG

springdoc:
  api-docs:
    path: ${API_DOCS_PATH}
  swagger-ui:
    path: ${SWAGGER_UI_PATH}